Vue.directive('transfer-dom', vuxTransferDom);

Vue.component('tabbar', vuxTabbar);
Vue.component('tabbar-item', vuxTabbarItem);
Vue.component('group', vuxGroup);
Vue.component('cell', vuxCell);
Vue.component('check-icon', vuxCheckIcon);
Vue.component('x-button', vuxXButton);
Vue.component('x-header', vuxXHeader);
Vue.component('view-box', vuxViewBox);
Vue.component('swipeout', vuxSwipeout);
Vue.component('swipeout-item', vuxSwipeoutItem);
Vue.component('swipeout-button', vuxSwipeoutButton);
Vue.component('popup', vuxPopup);
Vue.component('search', vuxSearch);
Vue.component('popover', vuxPopover);
Vue.component('divider', vuxDivider);
Vue.component('grid', vuxGrid);
Vue.component('grid-item', vuxGridItem);